### ISSUE TITLE
Node Modules and Package-lock not required

### ISSUE THREAD

**Issue by anjannair** [ColdSnow2/TModeration-Server#3]
Just wanted to point out use a file called `.gitignore` and add `node modules` and `package-lock.json` in it. A sample of this can be found in one of my projects [here](https://github.com/anjannair/Rufus-Discord-Bot/blob/master/.gitignore).

These are automatically generated by Node whenever your client installs dependencies.

**Comment by 4techguns** [comment]
we will make sure to add this in, however we're not sure if deleting the node_modules folder and package lock json would affect the repl though
however, we greatly appreciate help. thanks

**Comment by ColdSnow2** [comment]
Thanks for help us for changing the code. "package-lock.json" with me is very important. I just patched some errors that 4techguns created after create gitignore.

**Comment by anjannair** [comment]
@ColdSnow2 alright! I guess repl requires the `package-lock.json` file. But with a different hosting provider usually the lock-file is unnecessary.
