### ISSUE TITLE
major security flaw

### ISSUE THREAD

**Issue by 4techguns** [ColdSnow2/TModeration-Server#5]
![image](https://user-images.githubusercontent.com/42378704/177301196-cc807e54-45f2-4ed5-9180-145046233db7.png)
there is a command in the bot that can easily reveal your bot's eval token, allowing anyone to execute anything if they peer into the code.
my advice to you is to not use a password to access an eval command. it's too cumbersome and insecure to be even considered a security measure.
a suggestion would be to drop this eval password stuff altogether, and just check if the executing user is in a list of trusted user IDs
this is the only way to save your bot

**Comment by 4techguns** [comment]
on top of all that, don't just hardcode blocked users into your code. in the end, it'll get too messy, and isn't practical for keeping bad users out since they can just create alternate accounts and use those

**Comment by ColdSnow2** [comment]
i still can't figure out how they can find the secret command

**Comment by 4techguns** [comment]
you're committing it into your github repository
![image](https://user-images.githubusercontent.com/42378704/177302870-ca13c763-50fe-4383-ba5f-75d762bc27aa.png)
plus, even if you didn't commit it, someone could just go into the replit and see it for themselves

**Comment by ColdSnow2** [comment]
i've removed the easter egg, so there is no security flaw. you're opened this issue after i deleted the easter egg.

**Comment by 4techguns** [comment]
still, it's not secure enough. you should take my suggestion into consideration and stop making excuses for making your bot hilariously insecure just because you "want to impress birb because i can defeat hackers myself"

**Comment by ColdSnow2** [comment]
> still, it's not secure enough. you should take my suggestion into consideration and stop making excuses for making your bot hilariously insecure just because you "want to impress birb because i can defeat hackers myself"

but... yeah birb still dont like me (technically)
